### ISSUE TITLE
Change "composer update mirrors" to "composer update --lock"

### ISSUE THREAD

**Issue by ezzatron** [packagist/private-packagist-docs#2]
Please see composer/composer#7459.

I think it would be better to use `composer update --lock` in place of `composer update mirrors` on https://packagist.com/docs because `composer update --lock` is exactly the same, but actually documented, whereas `composer update mirrors` is not.

I would have submitted a PR, but it doesn't look like this repo actually contains the content of https://packagist.com/docs - if I can help by submitting a PR elsewhere, please let me know.

**Comment by naderman** [comment]
We're only slowly moving docs over here, and clearly also not monitoring issues properly, sorry for the slow response!

We intentionally use composer update mirrors to make it clearer what the goal of the command is. I think the proper thing to do is to document these aliases on Composer as well.

**Comment by naderman** [comment]
Made a Composer PR to address this https://github.com/composer/composer/pull/8855
