### ISSUE TITLE
Missing quote on documentation

### ISSUE THREAD

**Issue by acantepie** [packagist/private-packagist-docs#33]
Hello,

There is a missing quote here https://raw.githubusercontent.com/packagist/private-packagist-docs/master/docs/setup.md 
```
    ```
    "repositories": [
        {"type": "composer", "url": "https://repo.packagist.com/acme-company/},
        {"packagist.org": false}
    ]
    ```
```

**Comment by glaubinix** [comment]
Fixed with https://github.com/packagist/private-packagist-docs/commit/aaf8556ba88ff208472e80117891537c6898e7bf
